dist: xenial
sudo: required
cache: cargo
language: rust
addons:
  apt:
    packages:
      - kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
      # The version of kcov shipped with Xenial (v25) doesn't support the
      # --verify option that `cargo coveralls` passes. This PPA has a more
      # up-to-date version. It can be removed if Ubuntu ever ships a newer
      # version, or replaced with another PPA if this one falls out of date.
      - sourceline: ppa:sivakov512/kcov

rust:
  - stable

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - cargo install --force cargo-travis && export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add clippy rustfmt

script:
  # Clippy must be run first, as its lints are only triggered during
  # compilation. Put another way: after a successful `cargo build`, `cargo
  # clippy` is guaranteed to produce no results. This bug is known upstream:
  # https://github.com/rust-lang/rust-clippy/issues/2604.
  - travis-cargo clippy -- --all-targets --all-features -- -D warnings
  - travis-cargo build
  - travis-cargo test
  - travis-cargo fmt -- -- --check

after_success:
  - cargo coveralls --verbose

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
